// Generated by CoffeeScript 1.6.3
var HtmlCompiler;

module.exports = HtmlCompiler = (function() {
  HtmlCompiler.prototype.brunchPlugin = true;

  HtmlCompiler.prototype.type = 'template';

  HtmlCompiler.prototype.extension = 'html';

  function HtmlCompiler(config) {
    this.config = config;
    null;
  }

  HtmlCompiler.prototype.compile = function(data, path, callback) {
    var err, error;
    try {

    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, null);
    }
  };

  HtmlCompiler.prototype.onCompile = function(generatedFiles) {};

  return HtmlCompiler;

})();
